"""add_thong_so_ky_thuat_column

Revision ID: 4f248050f856
Revises: 93984d570012
Create Date: 2026-02-02 20:45:13.538289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f248050f856'
down_revision: Union[str, Sequence[str], None] = '93984d570012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chitietdonhang', 'gia_mua',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('chitietdonhang', 'thanh_tien',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('chitietdonhang', 'ten_sanpham',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_chitietdonhang_donhang'), table_name='chitietdonhang')
    op.create_index(op.f('ix_chitietdonhang_ma_ctdh'), 'chitietdonhang', ['ma_ctdh'], unique=False)
    op.drop_constraint(op.f('chitietdonhang_ma_don_hang_fkey'), 'chitietdonhang', type_='foreignkey')
    op.create_foreign_key(None, 'chitietdonhang', 'sanpham', ['ma_sanpham'], ['ma_sanpham'])
    op.create_foreign_key(None, 'chitietdonhang', 'donhang', ['ma_don_hang'], ['ma_don_hang'])
    op.alter_column('chitietgiohang', 'so_luong',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('chitietgiohang', 'gia_hien_tai',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_chitietgiohang_ma_ctgh'), 'chitietgiohang', ['ma_ctgh'], unique=False)
    op.drop_index(op.f('idx_danhgia_sanpham'), table_name='danhgia')
    op.drop_index(op.f('idx_danhgia_trangthai'), table_name='danhgia')
    op.create_index(op.f('ix_danhgia_ma_danhgia'), 'danhgia', ['ma_danhgia'], unique=False)
    op.create_index(op.f('ix_danhmuc_ma_danhmuc'), 'danhmuc', ['ma_danhmuc'], unique=False)
    op.alter_column('donhang', 'ngay_dat',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('donhang', 'tong_tien',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_donhang_ma_khuyenmai'), table_name='donhang')
    op.drop_index(op.f('idx_donhang_ngay'), table_name='donhang')
    op.drop_index(op.f('idx_donhang_trangthai'), table_name='donhang')
    op.drop_index(op.f('idx_donhang_user'), table_name='donhang')
    op.create_index(op.f('ix_donhang_ma_don_hang'), 'donhang', ['ma_don_hang'], unique=False)
    op.drop_constraint(op.f('fk_donhang_ma_khuyenmai'), 'donhang', type_='foreignkey')
    op.create_foreign_key(None, 'donhang', 'ma_khuyenmai', ['ma_khuyenmai'], ['ma_khuyenmai'])
    op.drop_constraint(op.f('dsyeuthich_ma_user_ma_sanpham_key'), 'dsyeuthich', type_='unique')
    op.create_index(op.f('ix_dsyeuthich_ma_dsyeuthich'), 'dsyeuthich', ['ma_dsyeuthich'], unique=False)
    op.alter_column('giohang', 'ngay_tao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_giohang_ma_gio'), 'giohang', ['ma_gio'], unique=False)
    op.drop_constraint(op.f('giohang_ma_user_fkey'), 'giohang', type_='foreignkey')
    op.create_foreign_key(None, 'giohang', 'users', ['ma_user'], ['ma_user'])
    op.create_index(op.f('ix_hinhanh_ma_anh'), 'hinhanh', ['ma_anh'], unique=False)
    op.create_index(op.f('ix_lichsuchat_id_chat'), 'lichsuchat', ['id_chat'], unique=False)
    op.create_index(op.f('ix_ma_khuyenmai_ma_khuyenmai'), 'ma_khuyenmai', ['ma_khuyenmai'], unique=False)
    op.add_column('sanpham', sa.Column('thong_so_ky_thuat', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('sanpham', 'gia',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('sanpham', 'gia_tri_giam',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sanpham', 'diem_danh_gia',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sanpham', 'ngay_lap',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_sanpham_active'), table_name='sanpham')
    op.drop_index(op.f('idx_sanpham_danhgia'), table_name='sanpham')
    op.drop_index(op.f('idx_sanpham_danhmuc'), table_name='sanpham')
    op.drop_index(op.f('idx_sanpham_gia'), table_name='sanpham')
    op.create_index(op.f('ix_sanpham_ma_sanpham'), 'sanpham', ['ma_sanpham'], unique=False)
    op.alter_column('thanhtoan', 'ma_don_hang',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('thanhtoan', 'ngay_thanhtoan',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('thanhtoan', 'pt_thanhtoan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'cod'::character varying"))
    op.alter_column('thanhtoan', 'trang_thai',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_thanhtoan_ma_thanhtoan'), 'thanhtoan', ['ma_thanhtoan'], unique=False)
    op.drop_constraint(op.f('thanhtoan_ma_don_hang_fkey'), 'thanhtoan', type_='foreignkey')
    op.create_foreign_key(None, 'thanhtoan', 'donhang', ['ma_don_hang'], ['ma_don_hang'])
    op.create_index(op.f('ix_thuonghieu_ma_thuonghieu'), 'thuonghieu', ['ma_thuonghieu'], unique=False)
    op.create_index(op.f('ix_tonkho_ma_tonkho'), 'tonkho', ['ma_tonkho'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_ma_user'), 'users', ['ma_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ma_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_tonkho_ma_tonkho'), table_name='tonkho')
    op.drop_index(op.f('ix_thuonghieu_ma_thuonghieu'), table_name='thuonghieu')
    op.drop_constraint(None, 'thanhtoan', type_='foreignkey')
    op.create_foreign_key(op.f('thanhtoan_ma_don_hang_fkey'), 'thanhtoan', 'donhang', ['ma_don_hang'], ['ma_don_hang'], ondelete='CASCADE')
    op.drop_index(op.f('ix_thanhtoan_ma_thanhtoan'), table_name='thanhtoan')
    op.alter_column('thanhtoan', 'trang_thai',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('thanhtoan', 'pt_thanhtoan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'cod'::character varying"))
    op.alter_column('thanhtoan', 'ngay_thanhtoan',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('thanhtoan', 'ma_don_hang',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_sanpham_ma_sanpham'), table_name='sanpham')
    op.create_index(op.f('idx_sanpham_gia'), 'sanpham', ['gia'], unique=False)
    op.create_index(op.f('idx_sanpham_danhmuc'), 'sanpham', ['ma_danhmuc'], unique=False)
    op.create_index(op.f('idx_sanpham_danhgia'), 'sanpham', [sa.literal_column('diem_danh_gia DESC')], unique=False)
    op.create_index(op.f('idx_sanpham_active'), 'sanpham', ['is_active'], unique=False)
    op.alter_column('sanpham', 'ngay_lap',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sanpham', 'diem_danh_gia',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sanpham', 'gia_tri_giam',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sanpham', 'gia',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('sanpham', 'thong_so_ky_thuat')
    op.drop_index(op.f('ix_ma_khuyenmai_ma_khuyenmai'), table_name='ma_khuyenmai')
    op.drop_index(op.f('ix_lichsuchat_id_chat'), table_name='lichsuchat')
    op.drop_index(op.f('ix_hinhanh_ma_anh'), table_name='hinhanh')
    op.drop_constraint(None, 'giohang', type_='foreignkey')
    op.create_foreign_key(op.f('giohang_ma_user_fkey'), 'giohang', 'users', ['ma_user'], ['ma_user'], ondelete='CASCADE')
    op.drop_index(op.f('ix_giohang_ma_gio'), table_name='giohang')
    op.alter_column('giohang', 'ngay_tao',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_dsyeuthich_ma_dsyeuthich'), table_name='dsyeuthich')
    op.create_unique_constraint(op.f('dsyeuthich_ma_user_ma_sanpham_key'), 'dsyeuthich', ['ma_user', 'ma_sanpham'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'donhang', type_='foreignkey')
    op.create_foreign_key(op.f('fk_donhang_ma_khuyenmai'), 'donhang', 'ma_khuyenmai', ['ma_khuyenmai'], ['ma_khuyenmai'], ondelete='SET NULL')
    op.drop_index(op.f('ix_donhang_ma_don_hang'), table_name='donhang')
    op.create_index(op.f('idx_donhang_user'), 'donhang', ['ma_user'], unique=False)
    op.create_index(op.f('idx_donhang_trangthai'), 'donhang', ['trang_thai'], unique=False)
    op.create_index(op.f('idx_donhang_ngay'), 'donhang', [sa.literal_column('ngay_dat DESC')], unique=False)
    op.create_index(op.f('idx_donhang_ma_khuyenmai'), 'donhang', ['ma_khuyenmai'], unique=False)
    op.alter_column('donhang', 'tong_tien',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('donhang', 'ngay_dat',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_danhmuc_ma_danhmuc'), table_name='danhmuc')
    op.drop_index(op.f('ix_danhgia_ma_danhgia'), table_name='danhgia')
    op.create_index(op.f('idx_danhgia_trangthai'), 'danhgia', ['trang_thai'], unique=False)
    op.create_index(op.f('idx_danhgia_sanpham'), 'danhgia', ['ma_sanpham'], unique=False)
    op.drop_index(op.f('ix_chitietgiohang_ma_ctgh'), table_name='chitietgiohang')
    op.alter_column('chitietgiohang', 'gia_hien_tai',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('chitietgiohang', 'so_luong',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'chitietdonhang', type_='foreignkey')
    op.drop_constraint(None, 'chitietdonhang', type_='foreignkey')
    op.create_foreign_key(op.f('chitietdonhang_ma_don_hang_fkey'), 'chitietdonhang', 'donhang', ['ma_don_hang'], ['ma_don_hang'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chitietdonhang_ma_ctdh'), table_name='chitietdonhang')
    op.create_index(op.f('idx_chitietdonhang_donhang'), 'chitietdonhang', ['ma_don_hang'], unique=False)
    op.alter_column('chitietdonhang', 'ten_sanpham',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('chitietdonhang', 'thanh_tien',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('chitietdonhang', 'gia_mua',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
