"""Add ngay_hoan_tien column to DonHang v2

Revision ID: d90c90120816
Revises: a453e49fc7f8
Create Date: 2026-03-23 08:46:27.421143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd90c90120816'
down_revision: Union[str, Sequence[str], None] = 'a453e49fc7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chitietdonhang_sanpham'), table_name='chitietdonhang')
    op.add_column('donhang', sa.Column('ngay_hoan_tien', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('lichsu_donhang', 'thoi_gian',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_lichsu_donhang_ma_don_hang'), 'lichsu_donhang', ['ma_don_hang'], unique=False)
    op.create_index(op.f('ix_lichsu_donhang_ma_lichsu'), 'lichsu_donhang', ['ma_lichsu'], unique=False)
    op.drop_constraint(op.f('fk_don_hang'), 'lichsu_donhang', type_='foreignkey')
    op.create_foreign_key(None, 'lichsu_donhang', 'donhang', ['ma_don_hang'], ['ma_don_hang'])
    op.alter_column('sanpham', 'ten_sanpham',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('sanpham', 'size_khung',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sanpham', 'mau',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sanpham', 'mau',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sanpham', 'size_khung',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sanpham', 'ten_sanpham',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'lichsu_donhang', type_='foreignkey')
    op.create_foreign_key(op.f('fk_don_hang'), 'lichsu_donhang', 'donhang', ['ma_don_hang'], ['ma_don_hang'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lichsu_donhang_ma_lichsu'), table_name='lichsu_donhang')
    op.drop_index(op.f('ix_lichsu_donhang_ma_don_hang'), table_name='lichsu_donhang')
    op.alter_column('lichsu_donhang', 'thoi_gian',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('donhang', 'ngay_hoan_tien')
    op.create_index(op.f('idx_chitietdonhang_sanpham'), 'chitietdonhang', ['ma_sanpham'], unique=False)
    # ### end Alembic commands ###
