"""fix_thong_so_ky_thuat_default_value

Revision ID: f19ce69bf2ef
Revises: 4f248050f856
Create Date: 2026-02-02 21:07:52.949403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19ce69bf2ef'
down_revision: Union[str, Sequence[str], None] = '4f248050f856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
